### ISSUE TITLE
Why vxgplayer keeps loading in https?

### ISSUE THREAD

**Issue by TinaC** [VideoExpertsGroup/Chrome-RTSP-Player#6]
[vxgplayer][1] demo works fine in HTTP, but in HTTPS it keeps loading , I am using 
`vxgplayer-1.8.21.js` in chrome, files in pnacl folder is successfully loadded.

The debug message output: 

    vxgplayer isFrame: false
    vxgplayer browserSupportsPluginPnacl: true
    Player vxg_media_player1 - init new player
    Player vxg_media_player1 handleMessage: Player Module is ready.
    Player vxg_media_player1 handleMessage: PLAYER_INITED
    Player vxg_media_player1 - moduleDidLoad
    Player vxg_media_player1 - loadSettings
    Player: vxg_media_player1 cmd=[setversion] 1.8.21
    Player: vxg_media_player1 cmd=[setconnection_timeout] 0
    Player: vxg_media_player1 cmd=[setaspectratio] 1
    Player: vxg_media_player1 cmd=[setavsync] 1
    Player: vxg_media_player1 cmd=[setlatency] 3000000
    Player vxg_media_player1 connectToApp
    Player vxg_media_player1 connected port=[object Object]
    connected port.name=1482113443000
    disconnected port.name=1482113443000

Why disconnected immedately after connected? 
  [1]: https://www.videoexpertsgroup.com/chrome-media-player-plug-in/

http://stackoverflow.com/questions/41214925/why-vxgplayer-keeps-loading-in-https

**Comment by bleikher** [comment]
Hi TinaC,
( duplicated in http://stackoverflow.com/questions/41214925/why-vxgplayer-keeps-loading-in-https/41216021#41216021 )
vxgplayer HTTPS page https://www.videoexpertsgroup.com/nacl_player_api/ should work as expected. vxgplayer works on HTTP webserver page without restrictions, but in order to enable vxgplayer onto your own HTTPS server you should send "top level domain" name like "https://yourcompany.com" to support@videoexpertsgroup.com for registration in the plugin.

Best Regards, VideoExpertsGroup Team
